export default new Map<string, string | { file: string }>(
    [
        ["pbjtime", { file: "./images/pbjtime.gif" }],
        ["👙 :beaver:", { file: "./images/beave.png" }],
        ["lenny", "( ͡° ͜ʖ ͡°)"],
        ["shrug", "¯\\_(ツ)_/¯"],
        ["justright", "✋😩👌"],
        ["tableflip", "(╯°□°）╯︵ ┻━┻"],
        ["unflip", "┬──┬  ノ( ゜-゜ノ)"],
        ["mmai1", "MegaMinerAI1 took place Spring 2008 and the game was Bombers"],
        ["mmai2", "MegaMinerAI2 took place Fall 2008 and the game was Elements"],
        ["mmai3", "MegaMinerAI3 took place Spring 2009 and the game was Zombies"],
        ["mmai4", "MegaMinerAI4 took place Fall 2009 and the game was Time Travel"],
        ["mmai5", "MegaMinerAI5 took place Spring 2010 and the game was Bloom"],
        ["mmai6", "MegaMinerAI6 took place Fall 2010 and the game was Modular"],
        ["mmai7", "MegaMinerAI7 took place Spring 2011 and the game was Piracy"],
        ["mmai8", "MegaMinerAI8 took place Fall 2011 and the game was Botnet"],
        ["mmai9", "MegaMinerAI9 took place Spring 2012 and the game was Space"],
        ["mmai10", "MegaMinerAI10 took place Fall 2012 and the game was Galapagos"],
        ["mmai11", "MegaMinerAI11 took place Spring 2013 and the game was Reef"],
        ["mmai12", "MegaMinerAI12 took place Fall 2013 and the game was Mars"],
        ["mmai13", "MegaMinerAI13 took place Spring 2014 and the game was Droids"],
        ["mmai14", "MegaMinerAI14 took place Fall 2014 and the game was Plants"],
        ["mmai15", "MegaMinerAI15 took place Spring 2015 and the game was Pharoah"],
        ["mmai16", "MegaMinerAI16 took place Fall 2015 and the game was Anarchy"],
        ["mmai17", "MegaMinerAI17 took place Spring 2016 and the game was Spiders"],
        ["mmai18", "MegaMinerAI18 took place Fall 2016 and the game was Saloon"],
        ["mmai19", "MegaMinerAI19 took place Spring 2017 and the game was Stumped"],
        ["mmai20", "MegaMinerAI20 took place Fall 2017 and the game was Catastrophe"],
        ["f", ":skull: rip :skull:"],
    ],
);
